version: "3.9"
name: "mongodb-stack"

services:
  mongodb-service:
    container_name: mongodb-container
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb-root-user
      - MONGO_INITDB_ROOT_PASSWORD=mongodb-root-pass
      - MONGO_INITDB_DATABASE=mydb
    ports:
      - 27017:27017
    volumes:
      - mongodb-volume:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mongodb-network

volumes:
  mongodb-volume:
    name: mongodb-volume

networks:
  mongodb-network:
    name: mongodb-network

#SUPER-ADMIN = mongodb://mongodb-root-user:mongodb-root-pass@localhost:27017
#DB-ADMIN = mongodb://db-user:db-pass@localhost:27017/mydb
